### ISSUE TITLE
Route ordering in swagger-json

### ISSUE THREAD

**Issue by lerouxrgd** [oliyh/pedestal-api#13]
Is it possible to get the routes in **swagger-json** in the same order as they are defined in the **terse table** ?
In the doc example pets get/put/delete queries get displayed in different order from the definition one.
It gets worse with more routes.

It looks like Pedestal's `expand-routes` preserves the route definition order, but not `api/swagger-json` ?
I suspect this is due to the [swagger-object](https://github.com/frankiesardo/route-swagger/blob/v0.1.0/src/route_swagger/doc.clj#L69) creation in `route-swagger`.

Do you have any thoughts on that?

**Comment by oliyh** [comment]
Hi, what is your use case out of interest? Do you want the Swagger UI to display in the same order as your declaration?

The swagger json spec defines the paths as a map so you'd be relying on ordered map implementations.

**Comment by lerouxrgd** [comment]
Hi, yes exactly I'd like to see the Swagger UI displaying routes in the same order as in my declarations. That's actually what I had with `compojure-api`.

Quickly looking at `compojure-api` internals it seems they use a [linked map](https://github.com/frankiesardo/linked) for extracting the paths (on [this](https://github.com/metosin/compojure-api/blob/master/src/compojure/api/routes.clj#L125) line).
I think this also makes the final swagger transformation-operation use a `linked map` since they call `empty` on the original `:paths` value ([this](https://github.com/metosin/ring-swagger/blob/master/src/ring/swagger/swagger2.clj#L166) line).

Maybe I'll try to do a similar thing in `route-swagger` as it doesn't seem possible to inject such a `linked map` from here.

**Comment by oliyh** [comment]
Sounds like this is a feature request for @frankiesardo in route-swagger

**Comment by oliyh** [comment]
Hi @lerouxrgd, this is now available in clojars as v0.3.0-SNAPSHOT.

**Comment by lerouxrgd** [comment]
Thank you!
