### ISSUE TITLE
s/with-fn-validation

### ISSUE THREAD

**Issue by orlin** [oliyh/pedestal-api#19]
Thanks for pedestal-api!  I’ve been using it for this [ephemeris-api](https://github.com/astrolin/ephemeris-api) the last couple of weeks.

A bit of a newbie question that’s probably obvious to you, I haven’t been able to turn on `(s/with-fn-validation …` in [service.clj](https://github.com/astrolin/ephemeris-api/blob/active/src/ephemeris_api/service.clj).  Looking at pedestal-api’s example and also spa-skeleton I can’t see what’s wrong with it.  Getting `Output of paths does not match schema ...` exception.

I’d appreciate if you could take a look.

**Comment by oliyh** [comment]
Hi @orlin,

I agree, it's not the easiest error message to read, but buried in there was the key which is that `:parameters` must be specified and must be a map.

Therefore the following code will make it work:
```clojure
{:summary   "Get the current mundane planetary positions."
 :parameters {}
 :responses {200 {:body Points}}}
```

I think I will make a change such that an empty parameters map is merged as the default, as I've been a victim of this myself in the past.

Hope this helps!

**Comment by orlin** [comment]
Thanks @oliyh, that did it!  Leaving the issue open in case you want a reminder about merging the empty parameters by default.  If you end-up adding that - would it be `handler`, `defhandler` or either?  I noticed the issue about *bad macros* and handlers becoming deprecated in pedestal so I guess your `handler` rather than pedestal's is more future-proof?

**Comment by oliyh** [comment]
Hi @orlin 

It's now done during route expansion as part of the `defroutes` macro as per https://github.com/oliyh/pedestal-api/commit/87dc39e1849a4932a928d7b82243226df904cfc9 so no need to worry about how you define your handlers. I'll do a release with this feature soon.

Glad I could help!
