### ISSUE TITLE
integrate route-swagger

### ISSUE THREAD

**Issue by lerouxrgd** [oliyh/pedestal-api#20]
Since it seems that route-swagger isn't being updated, as you can see with [this one-month old PR](https://github.com/frankiesardo/route-swagger/pull/34), would you consider integrate it directly into pedestal-api ?
The goal is to provide up-to-date dependencies on pedestal.

**Comment by oliyh** [comment]
Hi @lerouxrgd,

I've tried to contact Frankie but it seems like I could add a quick fix in pedestal-api so that people aren't blocked on upgrading pedestal.

**Comment by oliyh** [comment]
Hi @lerouxrgd 

I fixed this in `pedestal-api 0.3.2` instead, you can upgrade to this version along with `pedestal 0.5.3` and remove the hack.

Cheers

**Comment by lerouxrgd** [comment]
Excellent, thank you !

**Comment by oliyh** [comment]
Apologies, I made a mistake with the fix, and then made a subsequent mistake releasing the fixed version. Try `0.3.4`!
