### ISSUE TITLE
can we add description to parameters?

### ISSUE THREAD

**Issue by EMayej** [oliyh/pedestal-api#21]

**Comment by oliyh** [comment]
Hi @EMayej,

Yes, you can - you can add metadata to your schemas as follows:

```clojure
{:parameters
  {:query-params 
    {:page-size (with-meta s/Int
                           {:json-schema
                              {:description "Use this to limit the number of records returned by the query"}})}}}
```

You can add other elements from the Swagger description into `:json-schema` as well, they get merged with the auto-generated description.

Hope this helps

**Comment by EMayej** [comment]
it works. thank you.
